name = "meuwsic"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = ".next"

# R2 bucket bindings for Pages
[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "meuwsic-audio"

# Force deployment trigger